// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240719053829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Assignment", b =>
                {
                    b.Property<Guid>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("uuid");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            uuid = new Guid("0c212166-0eea-4e3a-b1d9-3b116e0a505a"),
                            Name = "Project Alpha",
                            dueDate = new DateTime(2024, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            startDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            uuid = new Guid("235bb79d-0342-406e-acf0-4b028bdf8c5e"),
                            Name = "Project Beta",
                            dueDate = new DateTime(2024, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            startDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            uuid = new Guid("f59dffff-6678-4b33-802b-615268c53a1e"),
                            Name = "Project Gamma",
                            dueDate = new DateTime(2024, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            startDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            uuid = new Guid("a229202f-35a9-4592-a096-9df65f1e5ca2"),
                            Name = "Project Delta",
                            dueDate = new DateTime(2025, 2, 28, 23, 59, 59, 0, DateTimeKind.Utc),
                            startDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WebApi.Models.Employee", b =>
                {
                    b.Property<Guid>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("uuid");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            uuid = new Guid("b6821df7-0c8d-47f8-aafe-4e20983a50e1"),
                            Age = 30,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            uuid = new Guid("ba25013a-7c4a-46ca-8ea6-b025f5377f52"),
                            Age = 25,
                            FirstName = "Anna",
                            LastName = "Karelia"
                        },
                        new
                        {
                            uuid = new Guid("c62d8880-c8e0-476b-8fc1-1a59fffe7124"),
                            Age = 40,
                            FirstName = "Michael",
                            LastName = "Smith"
                        },
                        new
                        {
                            uuid = new Guid("d6072945-4cb9-42fd-86de-b3b1e9059985"),
                            Age = 35,
                            FirstName = "Emily",
                            LastName = "Jones"
                        });
                });

            modelBuilder.Entity("WebApi.Models.EmployeeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AssignmentUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeUuid")
                        .HasColumnType("uuid");

                    b.Property<float>("HoursWorked")
                        .HasColumnType("real");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentUuid");

                    b.HasIndex("EmployeeUuid");

                    b.ToTable("EmployeeAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentUuid = new Guid("0c212166-0eea-4e3a-b1d9-3b116e0a505a"),
                            EmployeeUuid = new Guid("b6821df7-0c8d-47f8-aafe-4e20983a50e1"),
                            HoursWorked = 40f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AssignmentUuid = new Guid("235bb79d-0342-406e-acf0-4b028bdf8c5e"),
                            EmployeeUuid = new Guid("ba25013a-7c4a-46ca-8ea6-b025f5377f52"),
                            HoursWorked = 20f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AssignmentUuid = new Guid("f59dffff-6678-4b33-802b-615268c53a1e"),
                            EmployeeUuid = new Guid("c62d8880-c8e0-476b-8fc1-1a59fffe7124"),
                            HoursWorked = 30f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AssignmentUuid = new Guid("a229202f-35a9-4592-a096-9df65f1e5ca2"),
                            EmployeeUuid = new Guid("d6072945-4cb9-42fd-86de-b3b1e9059985"),
                            HoursWorked = 25f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AssignmentUuid = new Guid("f59dffff-6678-4b33-802b-615268c53a1e"),
                            EmployeeUuid = new Guid("b6821df7-0c8d-47f8-aafe-4e20983a50e1"),
                            HoursWorked = 15f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AssignmentUuid = new Guid("0c212166-0eea-4e3a-b1d9-3b116e0a505a"),
                            EmployeeUuid = new Guid("c62d8880-c8e0-476b-8fc1-1a59fffe7124"),
                            HoursWorked = 35f,
                            RecordedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApi.Models.EmployeeAssignment", b =>
                {
                    b.HasOne("WebApi.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
